export * from './by-role/by-role.component';
export * from './forms-demandas';
export * from './header/header.component';
export * from './lista-projetos/lista-projetos.component';
export * from './main/main.component';
export * from './meus-projetos/meus-projetos.component';
export * from './novo-projeto/novo-projeto.component';
export * from './pdf-viewer/pdf-viewer.component';
export * from './projeto-card/projeto-card.component';
