import { Projeto, Status } from "@app/shared/projeto.model";


export const projetos: Projeto[] = [
    {
        created: "2019-01-01",
        projetoId: 1,
        titulo: "Titulo A",
        tituloDesc: `Controle de Aterramentos Temporários: Tecnologia de IoT Aplicada para a 
        Eliminação de Desligamentos Indevidos pela Permanência dos Aterramentos Temporários.`,
        numero: "0001",
        empresaProponente: 1,
        status: Status.Proposta,
        segmentoId: 1,
        avaliacaoInicial: "",
        compartResultados: "",
        motivacao: "",
        originalidade: "",
        aplicabilidade: "",
        relevancia: "",
        razoabilidade: "",
        pesquisas: "",
        produtos: [],
    },
    {
        created: "2019-01-01",
        projetoId: 2,
        titulo: "Titulo B",
        tituloDesc: `Ferramenta para previsão de risco da ocorrência de fenômenos climatológicos 
        e alocação otimizada de recursos para manutenção emergencial de redes.`,
        numero: "0002",
        empresaProponente: 1,
        status: Status.Iniciado,
        segmentoId: 1,
        avaliacaoInicial: "",
        compartResultados: "",
        motivacao: "",
        originalidade: "",
        aplicabilidade: "",
        relevancia: "",
        razoabilidade: "",
        pesquisas: "",
        produtos: [],
    },
    {
        created: "2019-01-01",
        projetoId: 3,
        titulo: "Titulo C",
        tituloDesc: `Prospecção e Hierarquização de Inovações Tecnológicas Aplicadas a Equipamentos de Alta Tensão em Corrente Alternada`,
        numero: "0003",
        empresaProponente: 1,
        status: Status.Encerrado,
        segmentoId: 1,
        avaliacaoInicial: "",
        compartResultados: "",
        motivacao: "",
        originalidade: "",
        aplicabilidade: "",
        relevancia: "",
        razoabilidade: "",
        pesquisas: "",
        produtos: [],
    },
    {
        created: "2019-01-01",
        projetoId: 4,
        titulo: "Titulo D",
        tituloDesc: `Desenvolvimento de Tecnologia para Implementação de uma 
        Planta Termo-Solar de Cogeração no Município de Ribeiro Gonçalves`,
        numero: "0004",
        empresaProponente: 1,
        status: Status.Encerrado,
        segmentoId: 1,
        avaliacaoInicial: "",
        compartResultados: "",
        motivacao: "",
        originalidade: "",
        aplicabilidade: "",
        relevancia: "",
        razoabilidade: "",
        pesquisas: "",
        produtos: [],
    }
];
